// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwhjJYgw9c20HjfcgyBz5nAWfw--QA2Tk',
    appId: '1:118948846197:web:d46efb300ae09f8798363c',
    messagingSenderId: '118948846197',
    projectId: 'auctionproject-cea5a',
    authDomain: 'auctionproject-cea5a.firebaseapp.com',
    storageBucket: 'auctionproject-cea5a.appspot.com',
    measurementId: 'G-GHJP61J2Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZwZPObJxBftr9Pi9A7knWy0VGS9YRH3Y',
    appId: '1:118948846197:android:1b8d054a1645118398363c',
    messagingSenderId: '118948846197',
    projectId: 'auctionproject-cea5a',
    storageBucket: 'auctionproject-cea5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuFz9Xij9m1kb8EbizoJQEwDG8jk3uq7g',
    appId: '1:118948846197:ios:9b5c32ad5e9821b798363c',
    messagingSenderId: '118948846197',
    projectId: 'auctionproject-cea5a',
    storageBucket: 'auctionproject-cea5a.appspot.com',
    iosBundleId: 'com.example.auction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuFz9Xij9m1kb8EbizoJQEwDG8jk3uq7g',
    appId: '1:118948846197:ios:9b5c32ad5e9821b798363c',
    messagingSenderId: '118948846197',
    projectId: 'auctionproject-cea5a',
    storageBucket: 'auctionproject-cea5a.appspot.com',
    iosBundleId: 'com.example.auction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwhjJYgw9c20HjfcgyBz5nAWfw--QA2Tk',
    appId: '1:118948846197:web:3f9d0d6bd5515b2598363c',
    messagingSenderId: '118948846197',
    projectId: 'auctionproject-cea5a',
    authDomain: 'auctionproject-cea5a.firebaseapp.com',
    storageBucket: 'auctionproject-cea5a.appspot.com',
    measurementId: 'G-H5PPBZBZNZ',
  );

}